"""Typed state definition for the LangGraph state machine."""

from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages


class SessionState(TypedDict):
    """Complete state of an interview session.
    All nodes read/write to this state.
    """
    # Identification
    session_id: str
    client_profile: dict              # Profile of the client agent

    # Conversation
    transcript: list[dict]            # List of turns {role, content, turn_id, domain?}
    messages: Annotated[list, add_messages]  # LangChain messages

    # Coverage tracking
    domains_covered: list[str]        # Domains already evaluated
    domains_pending: list[str]        # Domains pending evaluation
    coverage_complete: bool           # Coverage complete flag

    # RAG context
    retrieved_chunks: list[dict]      # Latest context chunks retrieved
    query_history: list[str]          # Executed queries history

    # Diagnosis
    hypotheses: list[dict]            # Hypotheses generated by Diagnostician
    audit_report: dict | None         # Result from Evidence Auditor

    # Safety
    risk_detected: bool               # RiskGate flag
    risk_type: str | None

    # Control
    current_step: str                 # Current node
    turn_count: int                   # Number of conversation turns
    max_turns: int                    # Maximum allowed turns
    finalized: bool                   # Session finalized flag
    interactive_mode: bool            # True if human is acting as client
    language: str                     # Session language: "English" or "Español"
